### ISSUE TITLE
cmd-12 does not work on mac os x

### ISSUE THREAD

**Issue by edulis8** [damccull/sublimetext-SolarizedToggle#17]
I really wanted this to work. But cmd-12 does nothing.

**Comment by yanxun827** [comment]
Try fn+F12 on a mac.

**Comment by edulis8** [comment]
Doesn't work. Did I need to paste something into user preferences or is this supposed to work out of the box?

Best,
Eric Broberg
________________________________

**Comment by damccull** [comment]
This right here is supposed to make it work out of the box.
https://github.com/damccull/sublimetext-SolarizedToggle/blob/master/Default%20(OSX).sublime-keymap

 Honestly, though, I dont' have a mac and I haven't worked on this project in months and months. If you can figure out how to fix it, please feel free to send a pull request. I don't really have time to dig into it right now, and I apologize for that.

**Comment by edulis8** [comment]
Hi,
Thanks for your response and sorry for being rude. After re-installing it and changing the key binding, it works! Thanks.

**Comment by damccull** [comment]
I didn't think you were rude at all. I know there's a couple issues with the plugin, but I just haven't had the time or interest in fixing them. Maybe one day I will. Glad it's working, though. Have a great day!
