### ISSUE TITLE
Color scheme not working

### ISSUE THREAD

**Issue by tobia** [damccull/sublimetext-SolarizedToggle#18]
I just installed the latest SolarizedToggle from Package Control and set my user configuration as follows.

But the color scheme is not changed to the ones I set in `color_scheme_dark` and `color_scheme_dark`, instead it is changed to Solarized Light and Dark. The theme and font are changed correctly to the ones I set in the configuration.

    {
    	"color_scheme_dark": "Packages/Theme - Cobalt2/cobalt2.tmTheme",
    	"color_scheme_light": "Packages/Color Scheme - Default/Mac Classic.tmTheme",
    	"enable_font_switching": true,
    	"enable_theme_switching": true,
    	"font_face_dark": "GohuFont",
    	"font_face_light": "InconsolataGo",
    	"font_options_dark": ["no_italic", "no_antialias"],
    	"font_options_light": [],
    	"font_size_dark": 14,
    	"font_size_light": 14.0,
    	"solarized_toggle_mode": "light",
    	"theme_dark": "Cobalt2.sublime-theme",
    	"theme_light": "SoDaReloaded Light.sublime-theme"
    }

In the console I see the following lines, no error messages:

    reloading Packages/User/Preferences.sublime-settings
    reloading Packages/User/SolarizedToggle.sublime-settings
    reloading /Users/tobia/Library/Application Support/Sublime Text 3/Packages/User/Preferences.sublime-settings
    reloading /Users/tobia/Library/Application Support/Sublime Text 3/Packages/User/SolarizedToggle.sublime-settings

Why is it not reading my color schemes?

**Comment by damccull** [comment]
There's some variables you have there that I don't recognize. Are you putting the options in your main "Preferences.sublime-settings" file or in the SolarizedToggle.sublime-settings file?

You can access the SolarizedToggle.sublime-settings by clicking Preferences->Package Settings->SolarizedToggle->Settings - User

I've never tried to add the settings into a standard user file so I'm not even sure if that will work.

Something else to try is to make sure the path to the themes is exactly correct.

**Comment by tobia** [comment]
Yes, I'm using the correct settings file and putting the correct values.

After some more experimenting, I narrowed down the issue: it seems SolarizedToggle does not read the settings file after I save it (either the whole file or the color scheme setting.) I need to restart ST for all the changes to take effect.

**Comment by damccull** [comment]
Then this is related to #16. I'm going to go ahead and close this issue and we'll leave that bug report open until it's fixed. If you have any suggestions, please submit a PR or suggestions on #16.
